global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://web:80
    relabel_configs:
      # Send the target URL to blackbox exporter
      - source_labels: [__address__]
        target_label: __param_target

      # Show real target in Prometheus UI
      - source_labels: [__param_target]
        target_label: instance

      # Blackbox exporter service
      - target_label: __address__
        replacement: blackbox:9115
